# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('log_reg', '0004_auto_20160927_1712'),
        ('cool_app', '0002_auto_20160927_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='log_reg.User')),
            ],
        ),
        migrations.CreateModel(
            name='WishlistEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wisher', to='log_reg.User')),
                ('wishitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishitem', to='cool_app.Item')),
            ],
        ),
    ]
