# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg', '0003_auto_20160923_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='birthdate',
            new_name='hiredate',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='alias',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
